added cat modal
fxbits/snapcat pull request #26
Opened 2022-04-12 11:16 UTC by andrewdoro

2022-04-12 12:16 UTC, vasileorza requested changes

2022-04-12 12:16 UTC, vasileorza commented on components/Dropzone/Dropzone.tsx
> +}
Please rename file to `ImageUploadIcon` and move the `dropzoneChildren` logic to a dedicated file, in order to use a dedicated file for each React component.

2022-04-12 12:16 UTC, vasileorza commented on components/CatModal/CatModalHeader.tsx
> +  const theme = useMantineTheme();
This hook is redundant for the moment.

2022-04-12 12:16 UTC, vasileorza commented on components/ModalManager/ModalManager.tsx
> +    '& .mantine-Modal-modal': {
No changes required, just a question. What does the `&` character do in this context?

2022-04-13 07:05 UTC, florea-razvan requested changes

2022-04-13 07:05 UTC, florea-razvan commented on components/ModalManager/InterestZoneModalHeader.tsx
> +    [Status.DONE]: '#B0EF8F',
some constants need to be defined instead of using the colorcodes directly (for reusability)

2022-04-13 07:05 UTC, florea-razvan commented on components/ModalManager/InterestZoneModalHeader.tsx
> +      {modal.type === 'VIEW_ZONE' ? (
please define also an enum with the modal types ('VIEW_ZONE', 'EDIT_ZONE', etc)

2022-04-13 07:05 UTC, florea-razvan commented on package.json
>      "@mui/icons-material": "^5.5.1",
if we are no longer using @mui, these dependencies can be removed

2022-04-13 12:38 UTC, florea-razvan approved these changes

2022-04-13 12:42 UTC, vasileorza approved these changes

2022-04-13 12:42 UTC, merged