add endpoints for zone modification(deletion, editting, cat deletion,…
fxbits/snapcat pull request #27
Opened 2022-04-12 11:47 UTC by radufx

… cat editting, cat sterilizing)

2022-04-12 12:48 UTC, vasileorza requested changes

2022-04-12 12:48 UTC, vasileorza commented on pages/api/interest-zones/[id].ts
> +                const newInterestZone = await zoneService.editZone(req.query.id, req.body);
Please use the `get`, `update` and `delete` prefixes when possible

2022-04-12 12:48 UTC, vasileorza commented on pages/api/interest-zones/[id]/[catID].ts
> +                const newCat = await zoneService.editCat(req.query.id, req.query.catID, req.body);
Please use the get, update and delete prefixes when possible

2022-04-12 12:48 UTC, vasileorza commented on pages/api/interest-zones/[id]/[catID].ts
> +                    res.status(404).json({message: error.message});
Please confirm a 500 error would not be better suited, 404 should be returned when the target entity is not found

2022-04-12 12:48 UTC, vasileorza commented on pages/api/interest-zones/[id]/[catID].ts
> +                res.status(404).json({message: error.message})
Please confirm a 500 error would not be better suited

2022-04-12 12:48 UTC, vasileorza commented on pages/api/interest-zones/[id]/[catID].ts
> +                const newSterilizedCat = await zoneService.changeToSterilized(req.query.id, req.query.catID, req.body);
Renaming the above method `changeToSterilized` to `sterilizeCat` would be more in line with the other related methods.

2022-04-12 12:48 UTC, vasileorza commented on services/zone-service.ts
> +        if (interestZone === undefined) interestZone = await this.findById(zoneID);
Please add a `{  }` block above

2022-04-12 12:48 UTC, vasileorza commented on services/zone-service.ts
> +        if (!cat) throw new Error(`Cat with ${catID} not found`);
Please add a `{  }` above

2022-04-12 12:48 UTC, vasileorza commented on services/zone-service.ts
> +        if (!cat) throw new Error(ZoneError.CAT_NOT_FOUND);
Please add a { } above

2022-04-12 12:48 UTC, vasileorza commented on services/zone-service.ts
> +        return interestZone;
Please add an empty row in the block above, to group the lines of code into related blocks

2022-04-12 12:48 UTC, vasileorza commented on services/zone-service.ts
> +        if (!cat) throw new Error(`Cat with ${catID} not found`)
Please add a { } above

2022-04-12 12:48 UTC, vasileorza commented on services/zone-service.ts
> +            if (cat) interestZone.noUnsterilizedCats--;
Please add a { } above

2022-04-12 12:48 UTC, vasileorza commented on services/zone-service.ts
> +            if (cat) interestZone.noUnsterilizedCats--;
I am not sure we want to decrease the `noUnsterilizedCats` value, if an invalid cat id was provided

2022-04-12 12:48 UTC, vasileorza commented on services/zone-service.ts
> +            interestZone.noUnsterilizedCats++;
Can you please confirm that the field above is necessary? At first glance, it can be deduced from `interestZone.unsterilizedCats.length`

2022-04-13 07:16 UTC, florea-razvan commented on pages/api/interest-zones/index.ts
please leave some "TODOs" everywhere you've removed the Auth0 security constraints (so as we don't forget about them)

2022-04-13 07:17 UTC, florea-razvan commented on services/zone-service.ts
> +            name: newZone.address.name
is it necessary to have a separate field for the address name?

2022-04-13 07:19 UTC, florea-razvan commented on services/zone-service.ts
> +        interestZone.status = newZone.status;
interest zone = {...newZone} should have the same result as these assignments

2022-04-13 07:20 UTC, florea-razvan commented on services/zone-service.ts
> +        await interestZone.save();
didn't you mean cat.save()?

2022-04-13 07:44 UTC, florea-razvan approved these changes

2022-04-13 07:45 UTC, merged