cat actions
fxbits/snapcat pull request #29
Opened 2022-04-15 14:35 UTC by andrewdoro

2022-04-18 14:19 UTC, florea-razvan requested changes

2022-04-18 14:19 UTC, florea-razvan commented on components/CatModal/CatActions.tsx
> +      gender: form.values.gender,
please extract the code responsible for creating this body in a separate private function and call it for add / update / sterilize

2022-04-18 14:19 UTC, florea-razvan commented on components/CatModal/CatModalView.tsx
> +      sterilizedStatus: (cat as SterilizedCat)?.releaseDate ? 'sterilized' : 'unsterilized',
do not forget to use here the values of the enum defined at the first comment

2022-04-18 14:19 UTC, florea-razvan commented on components/InterestZoneView/SterilizedCat.tsx
> +  const [AddCat, UpdateCat, DeleteCat, SterilizeCat] = useCatActions(cat?._id!);
is SterilizeCat action needed?

2022-04-18 14:19 UTC, florea-razvan commented on styles/theme.ts
> -    green: [
I guess these were not supposed to be deleted

2022-04-19 07:36 UTC, florea-razvan requested changes

2022-04-19 07:36 UTC, florea-razvan commented on components/InterestZoneModal/SterilizedCat.tsx
> +                {new Date(cat?.hospitalizationDate || ' ').toLocaleDateString('en-GB')}
use new Date() as fallback

2022-04-19 07:42 UTC, florea-razvan approved these changes

2022-04-19 08:05 UTC, vasileorza requested changes

2022-04-19 08:05 UTC, vasileorza commented on components/CatModal/useCatActions.tsx
> +    let body: any = {
Please look into adding typing to both the `function` and the `body` constant

2022-04-19 08:05 UTC, vasileorza commented on components/HeaderGoogle/HeaderGoogle.tsx
> +    console.log(addressName);
Please remove redundant `log`

2022-04-19 08:05 UTC, vasileorza commented on components/CatModal/CatModalView.tsx
> +      }),
Not sure if it is an improvement, but I'd write the code as follows
`
initialValues: {
        gender: Gender.UNKNOWN,
        observations: 'Enter here any observations, notes, that might help identify the cat more accurately.',
        mediaLinks: [],
        ...(cat ?? {}),
        volunteerName: .........
`

2022-04-19 08:05 UTC, vasileorza commented on components/CatModal/CatModalView.tsx
> +              maxSize={3 * 1024 ** 2}
Please move the number to a constant

2022-04-19 08:31 UTC, merged