Add google maps
fxbits/snapcat pull request #3
Opened 2022-03-17 11:21 UTC by RazvanPop

Add google maps and 2 markers

2022-03-17 11:28 UTC, florea-razvan requested changes

2022-03-17 11:28 UTC, florea-razvan commented on package.json
> +    "@types/google-maps-react": "^2.0.5",
please remove this dependency and add it as a dev-dependency

2022-03-17 11:28 UTC, florea-razvan commented on pages/GoogleMap.tsx
> +  address:string;
please use indentation in between field name and field type

2022-03-17 11:28 UTC, florea-razvan commented on pages/GoogleMap.tsx
> +// const marker3 = new google.maps.LatLng(46.7545548,23.558355);
remove commented code

2022-03-17 11:28 UTC, florea-razvan commented on pages/GoogleMap.tsx
> +  // const onUnmount = React.useCallback(function callback(map)  {
commented code

2022-03-22 12:30 UTC, vasileorza commented on pages/GoogleMap.tsx
> +      });
Please favor using arrow functions instead of functions, whenever possible

2022-03-22 12:32 UTC, vasileorza commented on pages/GoogleMap.tsx
> +        coordinateToAddress(e.latLng);
Please move the contents of the method directly here, avoid defining methods outside react hooks.

2022-03-22 12:38 UTC, vasileorza commented on pages/GoogleMap.tsx
> +          });
Please remove the `marker` state, and copy the add marker directly here.

2022-03-23 12:19 UTC, vasileorza approved these changes

2022-03-23 12:20 UTC, merged